### PR TITLE
Fix libgdiplus to handle 2bpp color PNG files

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=27616.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
Build is green (status isn't getting updated due to ghprb bugs)  https://jenkins.mono-project.com/job/test-libgdiplus-pull-request/label=debian-amd64/6/

**Comment by migueldeicaza** [comment]
This looks fine.

**Pull request merged**
