### PR TITLE
Fix pango_MeasureCharacterRanges to work properly

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=26027.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by ermshiperete** [comment]
I included this change in PR #27

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
https://jenkins.mono-project.com/job/test-libgdiplus-pull-request/8/

**Comment by StephenMcConnel** [comment]
This has been replaced by PR #39, which includes this change.

**Pull request closed without merging**
