### PR TITLE
Fix no error when the font collection is null and the font doesn't exist

### LINKED ISSUE #161: GdipCreateFontFamilyFromName does not validate that the font exists if there is no collection
In `test_createFontFamilyFromName` in `testfont.c`

```
	// FIXME: Libgdiplus does not validate that the font family exists
	// if the collection is NULL.
#if defined(USE_WINDOWS_LIBGDIPLUS)
	status = GdipCreateFontFamilyFromName (NoSuchFont, NULL, &family);
	assertEqualInt (status, FontFamilyNotFound);
#endif
```

### PR DESCRIPTION
**Pull request by hughbe**
And delete dead code as a result

Fixes #161

### CODE REVIEW

**Comment by hughbe** [comment]
Relies on https://github.com/mono/libgdiplus/pull/221

**Comment by filipnavara** [comment]
The added test fails on OS X and Linux.

I am a bit torn on this one. On one hand I would very much like the mutexes gone and the font matching code unified. On the other hand I am worried that this will result in a performance regression.

**Comment by filipnavara** [comment]
The test actually fails because now the GdipGetGenericFontFamilySansSerif API fails. There's no "MS Sans Serif" on macOS by default.

**Comment by filipnavara** [comment]
I have added font substitution with FcConfigSubstitute and FcDefaultSubstitute to create_fontfamily_from_collection. Now it maps "MS Sans Serif" to "Bitstream Vera Sans" and still fails to find it. :-)

**Comment by hughbe** [comment]
I can't seem to figure this one out, so I'm gonna close it. Feel free to make an attempt fixing this differently if you want

**Comment by filipnavara** [comment]
It boils down to the fact that the available fonts on different platform are different. Since the main purpose of libgdiplus is to offer compatibility with existing code which is likely to use standard Windows font names there has to be some sort of mapping done. There are basically three ways how to do it:

- Use whatever FontConfig does and never fail to find a font
- Use your approach along with fallback mapping for common fonts on each supported platform (Windows, macOS, Linux w/ FreeDesktop base, any others?)
- Ship the Microsoft or Wine fonts as a fallback mechanism

The second approach is hard to maintain and requires us to do per-platform changes. The benefits may be negligible unless there's a compelling use case for the behavior. The third approach could be a nightmare when it comes to packaging and licensing requirements.

**Pull request closed without merging**
