### PR TITLE
Rewritten memory management of GpPath objects

### PR DESCRIPTION
**Pull request by filipnavara**
* Fixes issues #223, #224 and #225.
* Introduces out of memory checks for the path APIs.
* Optimises lot of the APIs to prevent unnecessary allocations, frees and copying.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@filipnavara is there a particular reason for "Remove G[Byte]Array code from GpPath objects and optimize the code"? It is touching a lot of code that I'm not familiar with :)

**Comment by filipnavara** [comment]
There's actually a couple of reasons, some of them objective, other subjective:

1. The G[Byte]Array have no way of handling out-of-memory situation gracefully. They just enter an infinite loop and freeze the application.
2. The g_array_append_val makes it easy to do a lot of reallocations resulting in an suboptimal code.
3. Old code actually did a LOT of unnecessary allocations/reallocations/copying.
4. I was fed up with glib dependency on Win32 / OS X and have a glib-free version of the code.

Admittedly the only objective reason is number 1. Number 2 and 3 could be solved while keeping the g_array_*, but it would result in a similarly big patch. Number 4 is moot for now, but maybe there would be some interest in that eventually.

**Comment by filipnavara** [comment]
I tested the code with libgdiplus test, Mono tests and KeePass running on OS X.

**Comment by akoeplinger** [comment]
Ok makes sense. Could you please rebase/squash the commits so we only have these:

- Remove G[Byte]Array code from GpPath objects and optimize the code
- Check for out-of-memory errors. Add missing copying in GdipCreatePath2.
- Fix memory leak in GdipFlattenPath and out-of-memory handling.
- Initial unit test for path functions.

**Comment by kasper3** [comment]
This is a great progress!
@filipnavara, is it towards dropping the dependency on glib?

**Comment by filipnavara** [comment]
@kasper3 I am no longer sure whether dropping GLib dependency is worth it. Yes, this patch goes a long way towards it. The remaining stuff is easy to rewrite too. Then again, if we decide to make use of Pango text rendering there will be an indirect dependency anyway.

**Comment by filipnavara** [comment]
I will do another rebase after https://github.com/mono/mono/pull/7943 is merged. Otherwise this is ready to be merged.

**Comment by hughbe** [comment]
What’s the status on this PR? Unfortunately if a PR adds a test file it will conflict with all others that add new test files so would be nice to merge these path test

**Comment by filipnavara** [comment]
Rebased.

**Pull request merged**
