### PR TITLE
 Add Graphics.Draw tests and fix argument validation

### LINKED ISSUE #423: GdipDrawCurve2 with a large tension differs from GDI+
### Code
```cpp
static void createImageGraphics (INT width, INT height, GpImage **image, GpGraphics **graphics)
{
	GpStatus status;

	status = GdipCreateBitmapFromScan0 (width, height, 0, PixelFormat32bppARGB, NULL, (GpBitmap **) image);
	assertEqualInt (status, Ok);

	status = GdipGetImageGraphicsContext (*image, graphics);
	assertEqualInt (status, Ok);
}

static void test_drawCurve2 ()
{
	GpStatus status;
	GpImage *image;
	GpGraphics *graphics;
	GpPen *pen;

	GdipCreatePen1 (0xFF00FF00, 1, UnitPixel, &pen);
	
	GpPointF normal7[] = {
		{10, 20},
		{60, 30},
		{60, 50},
		{80, 70},
		{100, 90},
		{150, 110},
		{200, 130},
	};

	// Small (3) - large tension.
	createImageGraphics (256, 256, &image, &graphics);
	status = GdipDrawCurve2 (graphics, pen, normal7, 3, 10);
	assertEqualInt (status, Ok);

	dumpImage (image);

	GdipDeleteGraphics (graphics);
	GdipDisposeImage (image);

	GdipDeleteGraphics (graphics);
	GdipDisposeImage (image);
}
```

(Ignoring the black background.)

#### GDI+
image

### Libgdiplus
test-image

### LINKED ISSUE #433: GdipFillClosedCurve2 does not implement any FillMode
Missing the parameter in implementation, but also needs to do some cairo stuff once validated

### PR DESCRIPTION
**Pull request by hughbe**
- Match the ordering of argument validation with GDI+
- Add missing argument validation
- Implement GdipFillClosedCurve2

Fixes #433
Fixes #423

### CODE REVIEW

**Comment by hughbe** [comment]
@akoeplinger hey do you think you could merge some of the open PRs - I don't want to be a pain in the ass but I have some work I want to make progress on but can't because I can't get my head around the mess of dependencies on other PRs :P

**Comment by filipnavara** [comment]
@hughbe I will go through the PRs later today and approve/comment them to make it for the maintainers easier to process.

**Comment by akoeplinger** [comment]
@hughbe sorry for the late reply, I just got back from vacation :) I pinged some people to take a look at the PRs, thanks!

**Comment by migueldeicaza** [comment]
This will need to be rebased

**Pull request merged**
